### ISSUE TITLE
./xoppylib/bin/linux/diff_pat GLIBC_2.29

### ISSUE THREAD

**Issue by schluenz** [oasys-kit/xoppylib#3]
hi,

the current version of diff_pat doesn't work on Centos_7 systems:

```
ldd ./xoppylib/bin/linux/diff_pat:
./xoppylib/bin/linux/diff_pat: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./xoppylib/bin/linux/diff_pat)
./xoppylib/bin/linux/diff_pat: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./xoppylib/bin/linux/diff_pat)

```

where could I find a centos_7 compatible binary (or the sources to recompile locally)?

**Comment by lucarebuffi** [comment]
Manolo, I confirm the issue:
![Screen Shot 2022-05-16 at 12 57 52 PM](https://user-images.githubusercontent.com/6713598/168654182-ce992915-af8b-4932-89f6-bf28740fc0ca.png)

**Comment by lucarebuffi** [comment]
I don't think RHEL7 can support glibc > 2.17, you maybe want to recompile the libraries in RHEL7 before releasing it.

**Comment by srio** [comment]
Hi, 
this is the always problematic case of linking with the right static libraries.
I recompiled diff_pat and tested the binary in a centos7 docker image, and should work now. 

To update, you need to manually upgrade the xoppylib package to the version 1.0.12. It is currently not automated in oasys (@lucarebuffi should xoppylib+dabax be added to the oasys-internal libraries?), so please do (after activating oasys miniconda)
```
python -m pip install xoppylib --upgrade
```
For info, the fortran sources are in  https://github.com/srio/crystal

**Comment by schluenz** [comment]
great, thanks for the quick fix! I can confirm that it works as expected. (I updated xoppy in oasys which also pulled xoppylib 1.0.12).
